// GENERATED — DO NOT EDIT
// Children generated by codegen/Generate.fsx from the Goo public surface.
namespace FunGoo

module Children =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type ButtonExtensions =
    [<Extension>]
    static member inline Children
      (this: Goo.Button, children: seq<Goo.Blob>)
      : Goo.Button =
      for v in children do
        this.Children.Add v

      this

    [<Extension>]
    static member inline Children
      (this: Goo.Button, [<ParamArray>] children: Goo.Blob[])
      : Goo.Button =
      for v in children do
        this.Children.Add v

      this

  [<Extension; Sealed>]
  type ContainerExtensions =
    [<Extension>]
    static member inline Children
      (this: Goo.Container, children: seq<Goo.Blob>)
      : Goo.Container =
      for v in children do
        this.Children.Add v

      this

    [<Extension>]
    static member inline Children
      (this: Goo.Container, [<ParamArray>] children: Goo.Blob[])
      : Goo.Container =
      for v in children do
        this.Children.Add v

      this
