// GENERATED — DO NOT EDIT
// Interop generated by codegen/Generate.fsx from the Goo public surface.

#nowarn "3391"
// GENERATED — DO NOT EDIT
// Interop generated by codegen/Generate.fsx from the Goo public surface.

#nowarn "3391"
namespace FunGoo

module Interop =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type InteropExtensions =
    [<Extension>]
    static member inline TryCopyTextRangeRects
      (
        this: Goo.ElementHandle,
        textRange: Goo.TextRange,
        space: Goo.TextCoordinateSpace,
        destination: Span<Goo.ElementRect>
      ) : int voption =
      let mutable value = Unchecked.defaultof<int>

      if this.TryCopyTextRangeRects(textRange, space, destination, &value) then
        ValueSome value
      else
        ValueNone

    [<Extension>]
    static member inline TryGetTextCaretRect
      (
        this: Goo.ElementHandle,
        position: Goo.TextPosition,
        space: Goo.TextCoordinateSpace
      ) : Goo.ElementRect voption =
      let mutable value = Unchecked.defaultof<Goo.ElementRect>

      if this.TryGetTextCaretRect(position, space, &value) then
        ValueSome value
      else
        ValueNone

    [<Extension>]
    static member inline TryGetTextPositionAt
      (this: Goo.ElementHandle, point: Goo.Point, space: Goo.TextCoordinateSpace) : Goo.TextPosition voption =
      let mutable value = Unchecked.defaultof<Goo.TextPosition>

      if this.TryGetTextPositionAt(point, space, &value) then
        ValueSome value
      else
        ValueNone

  let inline colorFromString(value: string) : Goo.Color = Goo.Color.Parse value
  let inline lengthFromFloat(value: float) : Goo.Length = value
  let inline lengthFromInt(value: int) : Goo.Length = value
