// GENERATED — DO NOT EDIT
// Interop generated by codegen/Generate.fsx from the Goo public surface.
namespace FunGoo

module Interop =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type InteropExtensions =
    [<Extension>]
    static member inline TryCopyTextRangeRects:
      this: Goo.ElementHandle *
      textRange: Goo.TextRange *
      space: Goo.TextCoordinateSpace *
      destination: Span<Goo.ElementRect> ->
        int voption

    [<Extension>]
    static member inline TryGetTextCaretRect:
      this: Goo.ElementHandle *
      position: Goo.TextPosition *
      space: Goo.TextCoordinateSpace ->
        Goo.ElementRect voption

    [<Extension>]
    static member inline TryGetTextPositionAt:
      this: Goo.ElementHandle *
      point: Goo.Point *
      space: Goo.TextCoordinateSpace ->
        Goo.TextPosition voption

  val inline colorFromString: value: string -> Goo.Color
  val inline lengthFromFloat: value: float -> Goo.Length
  val inline lengthFromInt: value: int -> Goo.Length
