// GENERATED — DO NOT EDIT
// Setters generated by codegen/Generate.fsx from the Goo public surface.
namespace FunGoo

module Setters =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type ShaderEffectExtensions =
    [<Extension>]
    static member inline ElapsedSeconds
      (this: Goo.ShaderEffect, elapsedSeconds: float)
      : Goo.ShaderEffect =
      this.ElapsedSeconds <- elapsedSeconds
      this

    [<Extension>]
    static member inline Playing
      (this: Goo.ShaderEffect, playing: bool)
      : Goo.ShaderEffect =
      this.Playing <- playing
      this

  [<Extension; Sealed>]
  type TextCommandEventExtensions =
    [<Extension>]
    static member inline Cancel
      (this: Goo.TextCommandEvent, cancel: bool)
      : Goo.TextCommandEvent =
      this.Cancel <- cancel
      this

  [<Extension; Sealed>]
  type TextEditorControllerExtensions =
    [<Extension>]
    static member inline OnCommand
      (this: Goo.TextEditorController, onCommand: Action<Goo.TextCommandEvent>)
      : Goo.TextEditorController =
      this.OnCommand <- onCommand
      this

    [<Extension>]
    static member inline OnSubmit
      (this: Goo.TextEditorController, onSubmit: System.Action)
      : Goo.TextEditorController =
      this.OnSubmit <- onSubmit
      this

    [<Extension>]
    static member inline Overwrite
      (this: Goo.TextEditorController, overwrite: bool)
      : Goo.TextEditorController =
      this.Overwrite <- overwrite
      this

    [<Extension>]
    static member inline Selection
      (this: Goo.TextEditorController, selection: Goo.TextSelection)
      : Goo.TextEditorController =
      this.Selection <- selection
      this

  [<Extension; Sealed>]
  type WindowExtensions =
    [<Extension>]
    static member inline AccessibilityAdapter
      (this: Goo.Window, accessibilityAdapter: Goo.AccessibilityAdapter)
      : Goo.Window =
      this.AccessibilityAdapter <- accessibilityAdapter
      this

    [<Extension>]
    static member inline Background
      (this: Goo.Window, background: Goo.Color)
      : Goo.Window =
      this.Background <- background
      this

    [<Extension>]
    static member inline Decorated
      (this: Goo.Window, decorated: bool)
      : Goo.Window =
      this.Decorated <- decorated
      this

    [<Extension>]
    static member inline Height(this: Goo.Window, height: int) : Goo.Window =
      this.Height <- height
      this

    [<Extension>]
    static member inline OnClosing
      (this: Goo.Window, onClosing: Func<bool>)
      : Goo.Window =
      this.OnClosing <- onClosing
      this

    [<Extension>]
    static member inline Resizable
      (this: Goo.Window, resizable: bool)
      : Goo.Window =
      this.Resizable <- resizable
      this

    [<Extension>]
    static member inline ResizeBand
      (this: Goo.Window, resizeBand: float32)
      : Goo.Window =
      this.ResizeBand <- resizeBand
      this

    [<Extension>]
    static member inline State
      (this: Goo.Window, state: Goo.WindowState)
      : Goo.Window =
      this.State <- state
      this

    [<Extension>]
    static member inline Title(this: Goo.Window, title: string) : Goo.Window =
      this.Title <- title
      this

    [<Extension>]
    static member inline Transparent
      (this: Goo.Window, transparent: bool)
      : Goo.Window =
      this.Transparent <- transparent
      this

    [<Extension>]
    static member inline VSync(this: Goo.Window, vSync: bool) : Goo.Window =
      this.VSync <- vSync
      this

    [<Extension>]
    static member inline Width(this: Goo.Window, width: int) : Goo.Window =
      this.Width <- width
      this

    [<Extension>]
    static member inline X(this: Goo.Window, x: int) : Goo.Window =
      this.X <- x
      this

    [<Extension>]
    static member inline Y(this: Goo.Window, y: int) : Goo.Window =
      this.Y <- y
      this
