// GENERATED — DO NOT EDIT
// Setters generated by codegen/Generate.fsx from the Goo public surface.
namespace FunGoo

module Setters =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type ShaderEffectExtensions =
    [<Extension>]
    static member inline ElapsedSeconds:
      this: Goo.ShaderEffect * elapsedSeconds: float -> Goo.ShaderEffect

    [<Extension>]
    static member inline Playing:
      this: Goo.ShaderEffect * playing: bool -> Goo.ShaderEffect

  [<Extension; Sealed>]
  type TextCommandEventExtensions =
    [<Extension>]
    static member inline Cancel:
      this: Goo.TextCommandEvent * cancel: bool -> Goo.TextCommandEvent

  [<Extension; Sealed>]
  type TextEditorControllerExtensions =
    [<Extension>]
    static member inline OnCommand:
      this: Goo.TextEditorController * onCommand: Action<Goo.TextCommandEvent> ->
        Goo.TextEditorController

    [<Extension>]
    static member inline OnSubmit:
      this: Goo.TextEditorController * onSubmit: System.Action ->
        Goo.TextEditorController

    [<Extension>]
    static member inline Overwrite:
      this: Goo.TextEditorController * overwrite: bool ->
        Goo.TextEditorController

    [<Extension>]
    static member inline Selection:
      this: Goo.TextEditorController * selection: Goo.TextSelection ->
        Goo.TextEditorController

  [<Extension; Sealed>]
  type WindowExtensions =
    [<Extension>]
    static member inline AccessibilityAdapter:
      this: Goo.Window * accessibilityAdapter: Goo.AccessibilityAdapter ->
        Goo.Window

    [<Extension>]
    static member inline Background:
      this: Goo.Window * background: Goo.Color -> Goo.Window

    [<Extension>]
    static member inline Decorated:
      this: Goo.Window * decorated: bool -> Goo.Window

    [<Extension>]
    static member inline Height: this: Goo.Window * height: int -> Goo.Window

    [<Extension>]
    static member inline OnClosing:
      this: Goo.Window * onClosing: Func<bool> -> Goo.Window

    [<Extension>]
    static member inline Resizable:
      this: Goo.Window * resizable: bool -> Goo.Window

    [<Extension>]
    static member inline ResizeBand:
      this: Goo.Window * resizeBand: float32 -> Goo.Window

    [<Extension>]
    static member inline State:
      this: Goo.Window * state: Goo.WindowState -> Goo.Window

    [<Extension>]
    static member inline Title: this: Goo.Window * title: string -> Goo.Window

    [<Extension>]
    static member inline Transparent:
      this: Goo.Window * transparent: bool -> Goo.Window

    [<Extension>]
    static member inline VSync: this: Goo.Window * vSync: bool -> Goo.Window

    [<Extension>]
    static member inline Width: this: Goo.Window * width: int -> Goo.Window

    [<Extension>]
    static member inline X: this: Goo.Window * x: int -> Goo.Window

    [<Extension>]
    static member inline Y: this: Goo.Window * y: int -> Goo.Window
