// GENERATED — DO NOT EDIT
// Widgets generated by codegen/Generate.fsx from the Goo.Widgets public surface.
namespace FunGoo

module Widgets =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type ActionButtonExtensions =
    [<Extension>]
    static member inline activeBackgroundColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.ActiveBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline activeTransform
      (
        this: Goo.Widgets.Actions.ActionButton,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.ActiveTransform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledBackgroundColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.DisabledBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledTextColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.DisabledTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusBorderColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.FocusBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline hoverBackgroundColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.HoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Actions.ActionButton,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Actions.ActionButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.ActionButton =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type IconButtonExtensions =
    [<Extension>]
    static member inline activeBackgroundColor
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.ActiveBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledOpacity
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.DisabledOpacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusOutlineColor
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.FocusOutlineColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline hoverBackgroundColor
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.HoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline padding
      (this: Goo.Widgets.Actions.IconButton, [<Struct>] ?value: float)
      : Goo.Widgets.Actions.IconButton =
      let mutable copy = this
      copy.Padding <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ColorPickerInputExtensions =
    [<Extension>]
    static member inline focusOutlineColor
      (this: Goo.Widgets.Colors.ColorPickerInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Colors.ColorPickerInput =
      let mutable copy = this
      copy.FocusOutlineColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Colors.ColorPickerInput, [<Struct>] ?value: float)
      : Goo.Widgets.Colors.ColorPickerInput =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline markerBorderColor
      (this: Goo.Widgets.Colors.ColorPickerInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Colors.ColorPickerInput =
      let mutable copy = this
      copy.MarkerBorderColor <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ChipExtensions =
    [<Extension>]
    static member inline activeBackgroundColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.ActiveBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline activeTransform
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.ActiveTransform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: float)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: float)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledOpacity
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: float)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.DisabledOpacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusBorderColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.FocusBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline hoverBackgroundColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.HoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: float)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedActiveBackgroundColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.SelectedActiveBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBackgroundColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.SelectedBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBorderColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.SelectedBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedHoverBackgroundColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.SelectedHoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedTextColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.SelectedTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Data.Chip, [<Struct>] ?value: float)
      : Goo.Widgets.Data.Chip =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type BadgeExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Feedback.Badge, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.Badge =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type BannerExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Feedback.Banner, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.Banner =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type DismissibleContextBarExtensions =
    [<Extension>]
    static member inline backgroundColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissActiveBackgroundColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissActiveBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissActiveTransform
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissActiveTransform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissBackgroundColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissBorderColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissBorderRadius
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissBorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissBorderWidth
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissBorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissDisabledBackgroundColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissDisabledBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissDisabledTextColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissDisabledTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissFocusBorderColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissFocusBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissHoverBackgroundColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissHoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline dismissTextColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.DismissTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Color
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Easing
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: float
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (
        this: Goo.Widgets.Feedback.DismissibleContextBar,
        [<Struct>] ?value: Goo.Length
      ) : Goo.Widgets.Feedback.DismissibleContextBar =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type EmptyStateExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline descriptionColor
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.DescriptionColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline minHeight
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.MinHeight <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline paddingHorizontal
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.PaddingHorizontal <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline paddingVertical
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.PaddingVertical <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textGap
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.TextGap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline titleColor
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.TitleColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Feedback.EmptyState,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Feedback.EmptyState, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Feedback.EmptyState =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ProgressBarExtensions =
    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Feedback.ProgressBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline fillColor
      (this: Goo.Widgets.Feedback.ProgressBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.FillColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Feedback.ProgressBar, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline trackColor
      (this: Goo.Widgets.Feedback.ProgressBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.TrackColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Feedback.ProgressBar,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Feedback.ProgressBar, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Feedback.ProgressBar, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.ProgressBar =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ProgressSummaryExtensions =
    [<Extension>]
    static member inline detailColor
      (this: Goo.Widgets.Feedback.ProgressSummary, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.ProgressSummary =
      let mutable copy = this
      copy.DetailColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Feedback.ProgressSummary, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.ProgressSummary =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline headerGap
      (this: Goo.Widgets.Feedback.ProgressSummary, [<Struct>] ?value: float)
      : Goo.Widgets.Feedback.ProgressSummary =
      let mutable copy = this
      copy.HeaderGap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline labelColor
      (this: Goo.Widgets.Feedback.ProgressSummary, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Feedback.ProgressSummary =
      let mutable copy = this
      copy.LabelColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Feedback.ProgressSummary, [<Struct>] ?value: Goo.Length) : Goo.Widgets.Feedback.ProgressSummary =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type GraphCanvasInputExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Graphs.GraphCanvasInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphCanvasInput =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline edgeColor
      (this: Goo.Widgets.Graphs.GraphCanvasInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphCanvasInput =
      let mutable copy = this
      copy.EdgeColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gridColor
      (this: Goo.Widgets.Graphs.GraphCanvasInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphCanvasInput =
      let mutable copy = this
      copy.GridColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline marqueeBorderColor
      (this: Goo.Widgets.Graphs.GraphCanvasInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphCanvasInput =
      let mutable copy = this
      copy.MarqueeBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline marqueeFillColor
      (this: Goo.Widgets.Graphs.GraphCanvasInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphCanvasInput =
      let mutable copy = this
      copy.MarqueeFillColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedEdgeColor
      (this: Goo.Widgets.Graphs.GraphCanvasInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphCanvasInput =
      let mutable copy = this
      copy.SelectedEdgeColor <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type GraphNodeCardExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: float)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: float)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline foregroundColor
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.ForegroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline padding
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: float)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.Padding <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBackgroundColor
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.SelectedBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBorderColor
      (this: Goo.Widgets.Graphs.GraphNodeCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Graphs.GraphNodeCard =
      let mutable copy = this
      copy.SelectedBorderColor <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type CheckboxExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline checkedBackgroundColor
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.CheckedBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline checkedBorderColor
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.CheckedBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledOpacity
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.DisabledOpacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline markColor
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.MarkColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Inputs.Checkbox, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Checkbox =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type SearchListExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusColor
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.FocusColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline height
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.Height <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline mutedColor
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.MutedColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline rowHeight
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.RowHeight <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedColor
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.SelectedColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Inputs.SearchList, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SearchList =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type SliderInputExtensions =
    [<Extension>]
    static member inline disabledOpacity
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.DisabledOpacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline fillColor
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.FillColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusOutlineColor
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.FocusOutlineColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline maximum
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.Maximum <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline minimum
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.Minimum <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline step
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.Step <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline thumbBorderColor
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.ThumbBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline thumbColor
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.ThumbColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline trackColor
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.TrackColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline trackRadius
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.TrackRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Inputs.SliderInput, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Inputs.SliderInput =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type StepperExtensions =
    [<Extension>]
    static member inline activeTextColor
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.ActiveTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline completedColor
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.CompletedColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline currentColor
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.CurrentColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline paddingHorizontal
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.PaddingHorizontal <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline upcomingColor
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.UpcomingColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline upcomingTextColor
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.UpcomingTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Inputs.Stepper, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Inputs.Stepper =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type TextFieldExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledBackgroundColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.DisabledBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledTextColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.DisabledTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.FocusColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusRingWidth
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.FocusRingWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline invalidColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.InvalidColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline mutedTextColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.MutedTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.PanelTransform) : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Inputs.TextField, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.TextField =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ToggleSwitchExtensions =
    [<Extension>]
    static member inline activeTransform
      (
        this: Goo.Widgets.Inputs.ToggleSwitch,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.ActiveTransform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledThumbColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.DisabledThumbColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline disabledTrackColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.DisabledTrackColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline focusBorderColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.FocusBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline offTrackColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.OffTrackColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline onThumbColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.OnThumbColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline onTrackColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.OnTrackColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline thumbColor
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.ThumbColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline thumbRadius
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.ThumbRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Inputs.ToggleSwitch,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Inputs.ToggleSwitch, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.ToggleSwitch =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type UploadTileExtensions =
    [<Extension>]
    static member inline actionInset
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.ActionInset <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline failedBorderColor
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.FailedBorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline padding
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.Padding <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline size
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.Size <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline statusBackgroundColor
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.StatusBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline statusPaddingHorizontal
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.StatusPaddingHorizontal <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline statusPaddingVertical
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.StatusPaddingVertical <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Inputs.UploadTile,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Inputs.UploadTile, [<Struct>] ?value: float)
      : Goo.Widgets.Inputs.UploadTile =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type AppBarExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline boxShadow
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.BoxShadow)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.BoxShadow <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline paddingHorizontal
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.PaddingHorizontal <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline subtitleColor
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.SubtitleColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline titleGap
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.TitleGap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Layout.AppBar, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Layout.AppBar =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type DrawerExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline boxShadow
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.BoxShadow)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.BoxShadow <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline closedOpacity
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.ClosedOpacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline closedTransform
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.ClosedTransform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline height
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.Height <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline openOpacity
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.OpenOpacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline openTransform
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.OpenTransform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Layout.Drawer, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.Drawer =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ListRowExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline captionColor
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.CaptionColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBackgroundColor
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.SelectedBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBoxShadow
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.BoxShadow)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.SelectedBoxShadow <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Layout.ListRow, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Layout.ListRow =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type MasterDetailExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Layout.MasterDetail, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.MasterDetail =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Layout.MasterDetail, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.MasterDetail =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Layout.MasterDetail, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.MasterDetail =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Layout.MasterDetail, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.MasterDetail =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Layout.MasterDetail, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.MasterDetail =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type ModalDialogExtensions =
    [<Extension>]
    static member inline backdropColor
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.BackdropColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline maxHeight
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.MaxHeight <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline padding
      (this: Goo.Widgets.Layout.ModalDialog, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.ModalDialog =
      let mutable copy = this
      copy.Padding <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type SectionHeaderExtensions =
    [<Extension>]
    static member inline accentColor
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.AccentColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline accentSize
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.AccentSize <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline expanded
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: bool)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.Expanded <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline labelColor
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.LabelColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline metaColor
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.MetaColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline ruleColor
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.RuleColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline ruleHeight
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: float)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.RuleHeight <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Layout.SectionHeader,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (this: Goo.Widgets.Layout.SectionHeader, [<Struct>] ?value: Goo.Length)
      : Goo.Widgets.Layout.SectionHeader =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type WindowChromeExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline closeHoverBackgroundColor
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.CloseHoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline controlColor
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.ControlColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline hoverBackgroundColor
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.HoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline isMaximized
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: bool)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.IsMaximized <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline showClose
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: bool)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.ShowClose <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline showMaximize
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: bool)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.ShowMaximize <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline showMinimize
      (this: Goo.Widgets.Layout.WindowChrome, [<Struct>] ?value: bool)
      : Goo.Widgets.Layout.WindowChrome =
      let mutable copy = this
      copy.ShowMinimize <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type AsyncImageExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: float)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderWidth
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: float)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.BorderWidth <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline errorTextColor
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.ErrorTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline fit
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.ImageFit)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.Fit <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: float)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline placeholderTextColor
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.PlaceholderTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.PanelTransform) : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionEasing
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: Goo.Easing)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.TransitionEasing <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transitionMs
      (this: Goo.Widgets.Media.AsyncImage, [<Struct>] ?value: float)
      : Goo.Widgets.Media.AsyncImage =
      let mutable copy = this
      copy.TransitionMs <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type AvatarExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderColor
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.BorderColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: float)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline fit
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: Goo.ImageFit)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.Fit <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: float)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (this: Goo.Widgets.Media.Avatar, [<Struct>] ?value: Goo.PanelTransform)
      : Goo.Widgets.Media.Avatar =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type MediaCardExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline borderRadius
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: float)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.BorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: float)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline hoverBackgroundColor
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.HoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline padding
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: float)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.Padding <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline supportingColor
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.SupportingColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline titleColor
      (this: Goo.Widgets.Media.MediaCard, [<Struct>] ?value: Goo.Color)
      : Goo.Widgets.Media.MediaCard =
      let mutable copy = this
      copy.TitleColor <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type MediaTransportInputExtensions =
    [<Extension>]
    static member inline actionBackgroundColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.ActionBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline actionGap
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: float)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.ActionGap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline actionHoverBackgroundColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.ActionHoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline canNext
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: bool)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.CanNext <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline canPlayPause
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: bool)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.CanPlayPause <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline canPrevious
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: bool)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.CanPrevious <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline canSeek
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: bool)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.CanSeek <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline canSetVolume
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: bool)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.CanSetVolume <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline fillColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.FillColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: float)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline padding
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: float)
      : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.Padding <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline primaryActionBackgroundColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.PrimaryActionBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline primaryActionTextColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.PrimaryActionTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline trackColor
      (this: Goo.Widgets.Media.MediaTransportInput, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.TrackColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline width
      (
        this: Goo.Widgets.Media.MediaTransportInput,
        [<Struct>] ?value: Goo.Length
      ) : Goo.Widgets.Media.MediaTransportInput =
      let mutable copy = this
      copy.Width <- ValueOption.toNullable value
      copy

  [<Extension; Sealed>]
  type NavigationRailExtensions =
    [<Extension>]
    static member inline backgroundColor
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.BackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline gap
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: float)
      : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.Gap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline height
      (
        this: Goo.Widgets.Navigation.NavigationRail,
        [<Struct>] ?value: Goo.Length
      ) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.Height <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline hoverBackgroundColor
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.HoverBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline itemBackgroundColor
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.ItemBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline itemBorderRadius
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: float)
      : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.ItemBorderRadius <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline itemGap
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: float)
      : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.ItemGap <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline itemPaddingHorizontal
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: float)
      : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.ItemPaddingHorizontal <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline opacity
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: float)
      : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.Opacity <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedBackgroundColor
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.SelectedBackgroundColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline selectedTextColor
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.SelectedTextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline textColor
      (this: Goo.Widgets.Navigation.NavigationRail, [<Struct>] ?value: Goo.Color) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.TextColor <- ValueOption.toNullable value
      copy

    [<Extension>]
    static member inline transform
      (
        this: Goo.Widgets.Navigation.NavigationRail,
        [<Struct>] ?value: Goo.PanelTransform
      ) : Goo.Widgets.Navigation.NavigationRail =
      let mutable copy = this
      copy.Transform <- ValueOption.toNullable value
      copy
