// GENERATED — DO NOT EDIT
// Widgets generated by codegen/Generate.fsx from the Goo.Widgets public surface.
namespace FunGoo

module Widgets =
  open System
  open System.Runtime.CompilerServices

  [<Extension; Sealed>]
  type ActionButtonExtensions =
    [<Extension>]
    static member inline activeBackgroundColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline activeTransform:
      this: Goo.Widgets.Actions.ActionButton *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline disabledBackgroundColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline disabledTextColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline focusBorderColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline hoverBackgroundColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Actions.ActionButton *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Actions.ActionButton

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Actions.ActionButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.ActionButton

  [<Extension; Sealed>]
  type IconButtonExtensions =
    [<Extension>]
    static member inline activeBackgroundColor:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.IconButton

    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.IconButton

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.IconButton

    [<Extension>]
    static member inline disabledOpacity:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.IconButton

    [<Extension>]
    static member inline focusOutlineColor:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.IconButton

    [<Extension>]
    static member inline hoverBackgroundColor:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Actions.IconButton

    [<Extension>]
    static member inline padding:
      this: Goo.Widgets.Actions.IconButton * [<Struct>] ?value: float ->
        Goo.Widgets.Actions.IconButton

  [<Extension; Sealed>]
  type ColorPickerInputExtensions =
    [<Extension>]
    static member inline focusOutlineColor:
      this: Goo.Widgets.Colors.ColorPickerInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Colors.ColorPickerInput

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Colors.ColorPickerInput * [<Struct>] ?value: float ->
        Goo.Widgets.Colors.ColorPickerInput

    [<Extension>]
    static member inline markerBorderColor:
      this: Goo.Widgets.Colors.ColorPickerInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Colors.ColorPickerInput

  [<Extension; Sealed>]
  type ChipExtensions =
    [<Extension>]
    static member inline activeBackgroundColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline activeTransform:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: float ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: float ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline disabledOpacity:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: float ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline focusBorderColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline hoverBackgroundColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: float ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline selectedActiveBackgroundColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline selectedBackgroundColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline selectedBorderColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline selectedHoverBackgroundColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline selectedTextColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Data.Chip

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Data.Chip * [<Struct>] ?value: float ->
        Goo.Widgets.Data.Chip

  [<Extension; Sealed>]
  type BadgeExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.Badge

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.Badge

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.Badge

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.Badge

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Feedback.Badge

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Feedback.Badge

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Feedback.Badge * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.Badge

  [<Extension; Sealed>]
  type BannerExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Feedback.Banner

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Feedback.Banner * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.Banner

  [<Extension; Sealed>]
  type DismissibleContextBarExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissActiveBackgroundColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissActiveTransform:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissBackgroundColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissBorderColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissBorderRadius:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissBorderWidth:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissDisabledBackgroundColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissDisabledTextColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissFocusBorderColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissHoverBackgroundColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline dismissTextColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.DismissibleContextBar

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Feedback.DismissibleContextBar *
      [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Feedback.DismissibleContextBar

  [<Extension; Sealed>]
  type EmptyStateExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline descriptionColor:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline minHeight:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline paddingHorizontal:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline paddingVertical:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline textGap:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline titleColor:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Feedback.EmptyState *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.EmptyState

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Feedback.EmptyState * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Feedback.EmptyState

  [<Extension; Sealed>]
  type ProgressBarExtensions =
    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Feedback.ProgressBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.ProgressBar

    [<Extension>]
    static member inline fillColor:
      this: Goo.Widgets.Feedback.ProgressBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.ProgressBar

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Feedback.ProgressBar * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.ProgressBar

    [<Extension>]
    static member inline trackColor:
      this: Goo.Widgets.Feedback.ProgressBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.ProgressBar

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Feedback.ProgressBar *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Feedback.ProgressBar

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Feedback.ProgressBar * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Feedback.ProgressBar

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Feedback.ProgressBar * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.ProgressBar

  [<Extension; Sealed>]
  type ProgressSummaryExtensions =
    [<Extension>]
    static member inline detailColor:
      this: Goo.Widgets.Feedback.ProgressSummary * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.ProgressSummary

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Feedback.ProgressSummary * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.ProgressSummary

    [<Extension>]
    static member inline headerGap:
      this: Goo.Widgets.Feedback.ProgressSummary * [<Struct>] ?value: float ->
        Goo.Widgets.Feedback.ProgressSummary

    [<Extension>]
    static member inline labelColor:
      this: Goo.Widgets.Feedback.ProgressSummary * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Feedback.ProgressSummary

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Feedback.ProgressSummary * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Feedback.ProgressSummary

  [<Extension; Sealed>]
  type GraphCanvasInputExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Graphs.GraphCanvasInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphCanvasInput

    [<Extension>]
    static member inline edgeColor:
      this: Goo.Widgets.Graphs.GraphCanvasInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphCanvasInput

    [<Extension>]
    static member inline gridColor:
      this: Goo.Widgets.Graphs.GraphCanvasInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphCanvasInput

    [<Extension>]
    static member inline marqueeBorderColor:
      this: Goo.Widgets.Graphs.GraphCanvasInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphCanvasInput

    [<Extension>]
    static member inline marqueeFillColor:
      this: Goo.Widgets.Graphs.GraphCanvasInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphCanvasInput

    [<Extension>]
    static member inline selectedEdgeColor:
      this: Goo.Widgets.Graphs.GraphCanvasInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphCanvasInput

  [<Extension; Sealed>]
  type GraphNodeCardExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: float ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: float ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline foregroundColor:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline padding:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: float ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline selectedBackgroundColor:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphNodeCard

    [<Extension>]
    static member inline selectedBorderColor:
      this: Goo.Widgets.Graphs.GraphNodeCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Graphs.GraphNodeCard

  [<Extension; Sealed>]
  type CheckboxExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline checkedBackgroundColor:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline checkedBorderColor:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline disabledOpacity:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline markColor:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Inputs.Checkbox

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Inputs.Checkbox * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Checkbox

  [<Extension; Sealed>]
  type SearchListExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline focusColor:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline height:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline mutedColor:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline rowHeight:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline selectedColor:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SearchList

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Inputs.SearchList * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SearchList

  [<Extension; Sealed>]
  type SliderInputExtensions =
    [<Extension>]
    static member inline disabledOpacity:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline fillColor:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline focusOutlineColor:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline maximum:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline minimum:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline step:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline thumbBorderColor:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline thumbColor:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline trackColor:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline trackRadius:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.SliderInput

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Inputs.SliderInput * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Inputs.SliderInput

  [<Extension; Sealed>]
  type StepperExtensions =
    [<Extension>]
    static member inline activeTextColor:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline completedColor:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline currentColor:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline paddingHorizontal:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline upcomingColor:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline upcomingTextColor:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.Stepper

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Inputs.Stepper * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Inputs.Stepper

  [<Extension; Sealed>]
  type TextFieldExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline disabledBackgroundColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline disabledTextColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline focusColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline focusRingWidth:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline invalidColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline mutedTextColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Inputs.TextField

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Inputs.TextField * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.TextField

  [<Extension; Sealed>]
  type ToggleSwitchExtensions =
    [<Extension>]
    static member inline activeTransform:
      this: Goo.Widgets.Inputs.ToggleSwitch *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline disabledThumbColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline disabledTrackColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline focusBorderColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline offTrackColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline onThumbColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline onTrackColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline thumbColor:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline thumbRadius:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Inputs.ToggleSwitch *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Inputs.ToggleSwitch

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Inputs.ToggleSwitch * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.ToggleSwitch

  [<Extension; Sealed>]
  type UploadTileExtensions =
    [<Extension>]
    static member inline actionInset:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline failedBorderColor:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline padding:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline size:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline statusBackgroundColor:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline statusPaddingHorizontal:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline statusPaddingVertical:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Inputs.UploadTile *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Inputs.UploadTile

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Inputs.UploadTile * [<Struct>] ?value: float ->
        Goo.Widgets.Inputs.UploadTile

  [<Extension; Sealed>]
  type AppBarExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline boxShadow:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.BoxShadow ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline paddingHorizontal:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline subtitleColor:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline titleGap:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Layout.AppBar

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Layout.AppBar * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Layout.AppBar

  [<Extension; Sealed>]
  type DrawerExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline boxShadow:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.BoxShadow ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline closedOpacity:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline closedTransform:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline height:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline openOpacity:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline openTransform:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Layout.Drawer

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Layout.Drawer * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.Drawer

  [<Extension; Sealed>]
  type ListRowExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline captionColor:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline selectedBackgroundColor:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline selectedBoxShadow:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.BoxShadow ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ListRow

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Layout.ListRow * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Layout.ListRow

  [<Extension; Sealed>]
  type MasterDetailExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Layout.MasterDetail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.MasterDetail

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Layout.MasterDetail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.MasterDetail

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Layout.MasterDetail * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.MasterDetail

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Layout.MasterDetail * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.MasterDetail

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Layout.MasterDetail * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.MasterDetail

  [<Extension; Sealed>]
  type ModalDialogExtensions =
    [<Extension>]
    static member inline backdropColor:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline maxHeight:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Layout.ModalDialog

    [<Extension>]
    static member inline padding:
      this: Goo.Widgets.Layout.ModalDialog * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.ModalDialog

  [<Extension; Sealed>]
  type SectionHeaderExtensions =
    [<Extension>]
    static member inline accentColor:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline accentSize:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline expanded:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: bool ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline labelColor:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline metaColor:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline ruleColor:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline ruleHeight:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: float ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Layout.SectionHeader *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Layout.SectionHeader

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Layout.SectionHeader * [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Layout.SectionHeader

  [<Extension; Sealed>]
  type WindowChromeExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline closeHoverBackgroundColor:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline controlColor:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline hoverBackgroundColor:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline isMaximized:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: bool ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline showClose:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: bool ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline showMaximize:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: bool ->
        Goo.Widgets.Layout.WindowChrome

    [<Extension>]
    static member inline showMinimize:
      this: Goo.Widgets.Layout.WindowChrome * [<Struct>] ?value: bool ->
        Goo.Widgets.Layout.WindowChrome

  [<Extension; Sealed>]
  type AsyncImageExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: float ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline borderWidth:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: float ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline errorTextColor:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline fit:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.ImageFit ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: float ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline placeholderTextColor:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline transitionEasing:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: Goo.Easing ->
        Goo.Widgets.Media.AsyncImage

    [<Extension>]
    static member inline transitionMs:
      this: Goo.Widgets.Media.AsyncImage * [<Struct>] ?value: float ->
        Goo.Widgets.Media.AsyncImage

  [<Extension; Sealed>]
  type AvatarExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.Avatar

    [<Extension>]
    static member inline borderColor:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.Avatar

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: float ->
        Goo.Widgets.Media.Avatar

    [<Extension>]
    static member inline fit:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: Goo.ImageFit ->
        Goo.Widgets.Media.Avatar

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: float ->
        Goo.Widgets.Media.Avatar

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.Avatar

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Media.Avatar * [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Media.Avatar

  [<Extension; Sealed>]
  type MediaCardExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaCard

    [<Extension>]
    static member inline borderRadius:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: float ->
        Goo.Widgets.Media.MediaCard

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: float ->
        Goo.Widgets.Media.MediaCard

    [<Extension>]
    static member inline hoverBackgroundColor:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaCard

    [<Extension>]
    static member inline padding:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: float ->
        Goo.Widgets.Media.MediaCard

    [<Extension>]
    static member inline supportingColor:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaCard

    [<Extension>]
    static member inline titleColor:
      this: Goo.Widgets.Media.MediaCard * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaCard

  [<Extension; Sealed>]
  type MediaTransportInputExtensions =
    [<Extension>]
    static member inline actionBackgroundColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline actionGap:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: float ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline actionHoverBackgroundColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline canNext:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: bool ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline canPlayPause:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: bool ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline canPrevious:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: bool ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline canSeek:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: bool ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline canSetVolume:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: bool ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline fillColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: float ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline padding:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: float ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline primaryActionBackgroundColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline primaryActionTextColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline trackColor:
      this: Goo.Widgets.Media.MediaTransportInput * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Media.MediaTransportInput

    [<Extension>]
    static member inline width:
      this: Goo.Widgets.Media.MediaTransportInput *
      [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Media.MediaTransportInput

  [<Extension; Sealed>]
  type NavigationRailExtensions =
    [<Extension>]
    static member inline backgroundColor:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline gap:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: float ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline height:
      this: Goo.Widgets.Navigation.NavigationRail *
      [<Struct>] ?value: Goo.Length ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline hoverBackgroundColor:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline itemBackgroundColor:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline itemBorderRadius:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: float ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline itemGap:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: float ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline itemPaddingHorizontal:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: float ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline opacity:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: float ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline selectedBackgroundColor:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline selectedTextColor:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline textColor:
      this: Goo.Widgets.Navigation.NavigationRail * [<Struct>] ?value: Goo.Color ->
        Goo.Widgets.Navigation.NavigationRail

    [<Extension>]
    static member inline transform:
      this: Goo.Widgets.Navigation.NavigationRail *
      [<Struct>] ?value: Goo.PanelTransform ->
        Goo.Widgets.Navigation.NavigationRail
